package POSTEST2;


import javax.swing.Icon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Resky Pahriyani
 */
public class output extends javax.swing.JFrame {

    /**
     * Creates new form output
     */
    public output() {
        initComponents();
    }

    public output(String Nama, String ttl, String tl, String JK, String Alamat, String RT, String RW, String desa, String Kec, String kota, String agama,String status, String godar,String pekerjaan,String kewarganegaraan)
         {
        initComponents();
        jLnamao.setText(Nama);
        jLtmpt.setText(ttl);
        jLtl.setText(tl);
        jLjko.setText(""+JK);
        jLalamato.setText(Alamat);
        jLrto.setText(RT);
        jLrw.setText(RW);
        jLdesao.setText(desa);
        jLkeco.setText(Kec);
        jLkotao.setText(kota);
        jLagamao.setText(""+agama);
        jLstatuso.setText(""+status);
        jLgodar.setText(""+godar);
        jLpekerjaano.setText(pekerjaan);
        jLkewarganegaraano.setText(""+kewarganegaraan);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public output(Icon pic){
    initComponents();
    label.setIcon(pic);
    
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLnama = new javax.swing.JLabel();
        jLttl = new javax.swing.JLabel();
        jLjk = new javax.swing.JLabel();
        jLalamat = new javax.swing.JLabel();
        jLrt = new javax.swing.JLabel();
        jLdesa = new javax.swing.JLabel();
        jLkec = new javax.swing.JLabel();
        jLkota = new javax.swing.JLabel();
        jLagama = new javax.swing.JLabel();
        jLstatus = new javax.swing.JLabel();
        jLpekerjaan = new javax.swing.JLabel();
        jLkewarganegaraan = new javax.swing.JLabel();
        jLtmpt = new javax.swing.JLabel();
        jLtl = new javax.swing.JLabel();
        jLjko = new javax.swing.JLabel();
        jLalamato = new javax.swing.JLabel();
        jLrto = new javax.swing.JLabel();
        jLrw = new javax.swing.JLabel();
        jLdesao = new javax.swing.JLabel();
        jLkeco = new javax.swing.JLabel();
        jLkotao = new javax.swing.JLabel();
        jLagamao = new javax.swing.JLabel();
        jLstatuso = new javax.swing.JLabel();
        jLpekerjaano = new javax.swing.JLabel();
        jLkewarganegaraano = new javax.swing.JLabel();
        jBexit = new javax.swing.JButton();
        jLnamao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLgodar = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Kartu Tanda Penduduk (KTP)");

        jLnama.setText("Nama");

        jLttl.setText("Tempat/Tanggal Lahir");

        jLjk.setText("Jenis Kelamin");

        jLalamat.setText("Alamat");

        jLrt.setText("RT/RW");

        jLdesa.setText("Kel/Desa");

        jLkec.setText("Kecamatan");

        jLkota.setText("Kota");

        jLagama.setText("Agama");

        jLstatus.setText("Status");

        jLpekerjaan.setText("Pekerjaan");

        jLkewarganegaraan.setText("Kewarganegaraan");

        jLtmpt.setText("jlabel3");

        jLtl.setText("jLabel4");

        jLjko.setText("jLabel5");

        jLalamato.setText("jLabel7");

        jLrto.setText("jLabel8");

        jLrw.setText("jLabel9");

        jLdesao.setText("jLabel10");

        jLkeco.setText("jLabel11");

        jLkotao.setText("jLabel12");

        jLagamao.setText("jLabel13");

        jLstatuso.setText("jLabel14");

        jLpekerjaano.setText("jLabel15");

        jLkewarganegaraano.setText("jLabel16");

        jBexit.setText("Exit");
        jBexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexitActionPerformed(evt);
            }
        });

        jLnamao.setText("jLabel2");

        jLabel2.setText("Golongan Darah");

        jLgodar.setText("jLabel3");

        label.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLnama)
                                            .addGap(146, 146, 146))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLttl)
                                                .addComponent(jLjk)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(29, 29, 29)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLkec)
                                                        .addComponent(jLdesa)
                                                        .addComponent(jLkota)
                                                        .addComponent(jLrt))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLalamat)
                                        .addGap(140, 140, 140)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLagama)
                                    .addGap(140, 140, 140)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLstatus)
                                .addGap(142, 142, 142)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLpekerjaan)
                            .addGap(125, 125, 125)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLkewarganegaraan)
                        .addGap(85, 85, 85)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLstatuso)
                    .addComponent(jLnamao)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLagamao)
                            .addComponent(jLalamato)
                            .addComponent(jLjko)
                            .addComponent(jLdesao)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLrto)
                                .addGap(37, 37, 37)
                                .addComponent(jLrw))
                            .addComponent(jLkeco)
                            .addComponent(jLkotao)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLtmpt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLtl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLpekerjaano)
                            .addComponent(jLgodar)
                            .addComponent(jLkewarganegaraano)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jBexit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnama)
                    .addComponent(jLnamao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLttl)
                            .addComponent(jLtmpt)
                            .addComponent(jLtl))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLjk)
                            .addComponent(jLjko))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLalamat)
                            .addComponent(jLalamato))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLrt)
                            .addComponent(jLrto)
                            .addComponent(jLrw))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLdesa)
                            .addComponent(jLdesao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLkec)
                            .addComponent(jLkeco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLkota)
                            .addComponent(jLkotao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLagama)
                            .addComponent(jLagamao)))
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLstatus)
                    .addComponent(jLstatuso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLgodar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLpekerjaan)
                    .addComponent(jLpekerjaano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLkewarganegaraan)
                    .addComponent(jLkewarganegaraano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jBexit)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new output().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLagama;
    private javax.swing.JLabel jLagamao;
    private javax.swing.JLabel jLalamat;
    private javax.swing.JLabel jLalamato;
    private javax.swing.JLabel jLdesa;
    private javax.swing.JLabel jLdesao;
    private javax.swing.JLabel jLgodar;
    private javax.swing.JLabel jLjk;
    private javax.swing.JLabel jLjko;
    private javax.swing.JLabel jLkec;
    private javax.swing.JLabel jLkeco;
    private javax.swing.JLabel jLkewarganegaraan;
    private javax.swing.JLabel jLkewarganegaraano;
    private javax.swing.JLabel jLkota;
    private javax.swing.JLabel jLkotao;
    private javax.swing.JLabel jLnama;
    private javax.swing.JLabel jLnamao;
    private javax.swing.JLabel jLpekerjaan;
    private javax.swing.JLabel jLpekerjaano;
    private javax.swing.JLabel jLrt;
    private javax.swing.JLabel jLrto;
    private javax.swing.JLabel jLrw;
    private javax.swing.JLabel jLstatus;
    private javax.swing.JLabel jLstatuso;
    private javax.swing.JLabel jLtl;
    private javax.swing.JLabel jLtmpt;
    private javax.swing.JLabel jLttl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
