package POSTEST2;


import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Resky Pahriyani
 */
public class postest2 extends javax.swing.JFrame {

    private String kec;

    /**
     * Creates new form postest2
     */
    public postest2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJK = new javax.swing.ButtonGroup();
        buttonGroupkewarganegaraan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLformktp = new javax.swing.JLabel();
        jLformisian = new javax.swing.JLabel();
        jLnama = new javax.swing.JLabel();
        jLttl = new javax.swing.JLabel();
        jLjk = new javax.swing.JLabel();
        jLalamat = new javax.swing.JLabel();
        jLrt = new javax.swing.JLabel();
        jLdesa = new javax.swing.JLabel();
        jLkecamatan = new javax.swing.JLabel();
        jLkota = new javax.swing.JLabel();
        jLagama = new javax.swing.JLabel();
        jLstatus = new javax.swing.JLabel();
        jLgoldar = new javax.swing.JLabel();
        jLpekerjaan = new javax.swing.JLabel();
        jLkewarganegaraan = new javax.swing.JLabel();
        jRBperempuan = new javax.swing.JRadioButton();
        jTFnama = new javax.swing.JTextField();
        jTFttl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFtl = new javax.swing.JTextField();
        jTFalamat = new javax.swing.JTextField();
        jTFRT = new javax.swing.JTextField();
        jTFRW = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRBlaki = new javax.swing.JRadioButton();
        jTFkec = new javax.swing.JTextField();
        jTFdesa = new javax.swing.JTextField();
        jTFkota = new javax.swing.JTextField();
        jCBagama = new javax.swing.JComboBox<>();
        jCBstatus = new javax.swing.JComboBox<>();
        jCBgodar = new javax.swing.JComboBox<>();
        jRBwna = new javax.swing.JRadioButton();
        jRBwni = new javax.swing.JRadioButton();
        jTFpekerjaan = new javax.swing.JTextField();
        jBreset = new javax.swing.JButton();
        jBregister = new javax.swing.JButton();
        jLfoto = new javax.swing.JLabel();
        jBchoose = new javax.swing.JButton();
        jLpoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLformktp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLformktp.setText("FORM KARTU TANDA PENDUDUK");

        jLformisian.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLformisian.setForeground(new java.awt.Color(255, 255, 255));
        jLformisian.setText("FORM ISIAN");

        jLnama.setText("Nama");

        jLttl.setText("Tempat/Tanggal Lahir");

        jLjk.setText("Jenis Kelamin");

        jLalamat.setText("Alamat");

        jLrt.setText("RT/RW");

        jLdesa.setText("Kel/Desa");

        jLkecamatan.setText("Kecamatan");

        jLkota.setText("Kota");

        jLagama.setText("Agama");

        jLstatus.setText("Status");

        jLgoldar.setText("Golongan Darah");

        jLpekerjaan.setText("Pekerjaan");

        jLkewarganegaraan.setText("Kewarganegaraan");

        buttonGroupJK.add(jRBperempuan);
        jRBperempuan.setText("Perempuan");

        jLabel1.setText("/");

        jTFtl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFtlActionPerformed(evt);
            }
        });

        jLabel2.setText("/");

        buttonGroupJK.add(jRBlaki);
        jRBlaki.setText("Laki-laki");

        jCBagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISLAM", "KRISTEN", "BUDHA", "KATOLIK", " " }));

        jCBstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KAWIN", "BELUM KAWIN" }));

        jCBgodar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));

        buttonGroupkewarganegaraan.add(jRBwna);
        jRBwna.setText("WNA");

        buttonGroupkewarganegaraan.add(jRBwni);
        jRBwni.setText("WNI");
        jRBwni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBwniActionPerformed(evt);
            }
        });

        jBreset.setText("Reset");
        jBreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBresetActionPerformed(evt);
            }
        });

        jBregister.setText("Register");
        jBregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregisterActionPerformed(evt);
            }
        });

        jLfoto.setText("FOTO");

        jBchoose.setText("Choose");
        jBchoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBchooseActionPerformed(evt);
            }
        });

        jLpoto.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLformktp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLformisian)))
                .addGap(56, 427, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBreset)
                .addGap(18, 18, 18)
                .addComponent(jBregister)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLnama)
                            .addComponent(jLttl)
                            .addComponent(jLjk)
                            .addComponent(jLalamat)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLdesa)
                            .addComponent(jLrt)
                            .addComponent(jLkecamatan)
                            .addComponent(jLkota)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLagama))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLstatus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLgoldar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLkewarganegaraan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLpekerjaan)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTFkota, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFkec, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFalamat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBstatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBgodar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBagama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFRT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(jTFRW, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jRBwna)
                        .addGap(18, 18, 18)
                        .addComponent(jRBwni))
                    .addComponent(jTFnama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBlaki, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFttl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBperempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFtl, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                    .addComponent(jTFdesa)
                    .addComponent(jTFpekerjaan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBchoose)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLfoto)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLpoto, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLformktp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLformisian)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnama)
                    .addComponent(jTFnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLttl)
                            .addComponent(jTFttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLjk)
                            .addComponent(jRBperempuan)
                            .addComponent(jRBlaki))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLalamat)
                            .addComponent(jTFalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLrt)
                            .addComponent(jTFRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFRW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLdesa)
                            .addComponent(jTFdesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLkecamatan)
                            .addComponent(jTFkec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLkota)
                            .addComponent(jTFkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLagama)
                            .addComponent(jCBagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLstatus)
                            .addComponent(jCBstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLgoldar)
                            .addComponent(jCBgodar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLpekerjaan)
                            .addComponent(jTFpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLkewarganegaraan)
                            .addComponent(jRBwna)
                            .addComponent(jRBwni)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLfoto)
                        .addGap(18, 18, 18)
                        .addComponent(jLpoto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBchoose)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBreset)
                    .addComponent(jBregister)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBwniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBwniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBwniActionPerformed

    private void jBresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBresetActionPerformed
        // TODO add your handling code here:
        jTFnama.setText("");
        jTFttl.setText("");
        jTFtl.setText("");
        buttonGroupJK.clearSelection();
        jTFalamat.setText("");
        jTFRT.setText("");
        jTFRW.setText("");
        jTFdesa.setText("");
        jTFkec.setText("");
        jTFkota.setText("");
        jCBagama.setSelectedItem(null);
        jCBstatus.setSelectedItem(null);
        jCBgodar.setSelectedItem(null);
        jTFpekerjaan.setText("");
        buttonGroupkewarganegaraan.clearSelection();
    }//GEN-LAST:event_jBresetActionPerformed

    private void jBregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregisterActionPerformed
        // TODO add your handling code here:
        String Nama, ttl, tl, JK=null, Alamat, RT, RW, desa, Kec, kota, agama, status, godar, pekerjaan;
        Nama = jTFnama.getText();
        ttl = jTFttl.getText();
        tl = jTFtl.getText();
            if (jRBlaki.isSelected())
            {JK = jRBlaki.getText();}
            else if (jRBperempuan.isSelected())
            {JK =jRBperempuan.getText();}
        Alamat =jTFalamat.getText();
        RT = jTFRT.getText();
        RW = jTFRW.getText();
        desa = jTFdesa.getText();
        Kec = jTFkec.getText();
        kota = jTFkota.getText();
        agama = jCBagama.getSelectedItem().toString();
        status = jCBstatus.getSelectedItem().toString();
        godar = jCBgodar.getSelectedItem().toString();
        pekerjaan = jTFpekerjaan.getText();
        String kewarganegaraan=null;
            if (jRBwna.isSelected())
            {kewarganegaraan = jRBwni.getText();}
            else if (jRBwni.isSelected())
            {kewarganegaraan = jRBwna.getText();}
            
       
       output x = new output(Nama, ttl, tl, JK, Alamat, RT, RW, desa, Kec, kota, agama, status, godar, pekerjaan, kewarganegaraan);
        x.setVisible(true);
    }//GEN-LAST:event_jBregisterActionPerformed

    private void jTFtlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFtlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFtlActionPerformed

    private void jBchooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBchooseActionPerformed
        // TODO add your handling code here:
        JFileChooser OPEN = new JFileChooser();
        int returnVal = OPEN.showOpenDialog(null);
        
        File filegambar = null;
        if (returnVal == JFileChooser.APPROVE_OPTION){
            filegambar=OPEN.getSelectedFile();
            String filename = filegambar.getAbsolutePath();
        }
        try {
            BufferedImage gambar=ImageIO.read(filegambar);
            ImageIcon icon=new ImageIcon(gambar.getScaledInstance(180,240,0));
            jLpoto.setIcon(icon);
            output outt =new output(icon);
            outt.setVisible(true);
            
        }
        catch (IOException e){e.getMessage();}
    }//GEN-LAST:event_jBchooseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(postest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(postest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(postest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(postest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new postest2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupJK;
    private javax.swing.ButtonGroup buttonGroupkewarganegaraan;
    private javax.swing.JButton jBchoose;
    private javax.swing.JButton jBregister;
    private javax.swing.JButton jBreset;
    private javax.swing.JComboBox<String> jCBagama;
    private javax.swing.JComboBox<String> jCBgodar;
    private javax.swing.JComboBox<String> jCBstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLagama;
    private javax.swing.JLabel jLalamat;
    private javax.swing.JLabel jLdesa;
    private javax.swing.JLabel jLformisian;
    private javax.swing.JLabel jLformktp;
    private javax.swing.JLabel jLfoto;
    private javax.swing.JLabel jLgoldar;
    private javax.swing.JLabel jLjk;
    private javax.swing.JLabel jLkecamatan;
    private javax.swing.JLabel jLkewarganegaraan;
    private javax.swing.JLabel jLkota;
    private javax.swing.JLabel jLnama;
    private javax.swing.JLabel jLpekerjaan;
    private javax.swing.JLabel jLpoto;
    private javax.swing.JLabel jLrt;
    private javax.swing.JLabel jLstatus;
    private javax.swing.JLabel jLttl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBlaki;
    private javax.swing.JRadioButton jRBperempuan;
    private javax.swing.JRadioButton jRBwna;
    private javax.swing.JRadioButton jRBwni;
    private javax.swing.JTextField jTFRT;
    private javax.swing.JTextField jTFRW;
    private javax.swing.JTextField jTFalamat;
    private javax.swing.JTextField jTFdesa;
    private javax.swing.JTextField jTFkec;
    private javax.swing.JTextField jTFkota;
    private javax.swing.JTextField jTFnama;
    private javax.swing.JTextField jTFpekerjaan;
    private javax.swing.JTextField jTFtl;
    private javax.swing.JTextField jTFttl;
    // End of variables declaration//GEN-END:variables

    private static class outputktp {

        public outputktp() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
