/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POSTEST3;

import POSTEST2.output;
import java.awt.image.BufferedImage;   //mengimport atau memanggil data/fungsi yang ada di java.awt.image.BufferedImage
import java.io.File;  //mengimport atau memanggil data/fungsi yang ada di java.io.File
import java.io.IOException;  //mengimport atau memanggil data/fungsi yang ada di java.io.IOException
import javax.imageio.ImageIO;  //mengimport atau memanggil data/fungsi yang ada di javax.imageio.ImageIO 
import javax.swing.ImageIcon;  //mengimport atau memanggil data/fungsi yang ada di javax.swing.ImageIcon
import javax.swing.JFileChooser;  //mengimport atau memanggil data/fungsi yang ada di javax.swing.JFileChooser

/**
 *
 * @author Resky Pahriyani
 */
public class postest3 extends javax.swing.JFrame {  //class turunan dari javax.swing.JFrame, artinya class POSTTEST3 dapat mengakses data/fungsi yang ada di parentnya javax.swing.JFrame

    /**
     * Creates new form postest3
     */
    public postest3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPform = new javax.swing.JPanel();
        jLformktp1 = new javax.swing.JLabel();
        jLformisian1 = new javax.swing.JLabel();
        jLnama1 = new javax.swing.JLabel();
        jLttl1 = new javax.swing.JLabel();
        jLjk1 = new javax.swing.JLabel();
        jLalamat1 = new javax.swing.JLabel();
        jLrt1 = new javax.swing.JLabel();
        jLdesa1 = new javax.swing.JLabel();
        jLkecamatan1 = new javax.swing.JLabel();
        jLkota1 = new javax.swing.JLabel();
        jLagama1 = new javax.swing.JLabel();
        jLstatus1 = new javax.swing.JLabel();
        jLgoldar1 = new javax.swing.JLabel();
        jLpekerjaan1 = new javax.swing.JLabel();
        jLkewarganegaraan1 = new javax.swing.JLabel();
        jRBperempuan1 = new javax.swing.JRadioButton();
        jTFnama1 = new javax.swing.JTextField();
        jTFttl1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFtl1 = new javax.swing.JTextField();
        jTFalamat1 = new javax.swing.JTextField();
        jTFRT1 = new javax.swing.JTextField();
        jTFRW1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRBlaki1 = new javax.swing.JRadioButton();
        jTFkec1 = new javax.swing.JTextField();
        jTFdesa1 = new javax.swing.JTextField();
        jTFkota1 = new javax.swing.JTextField();
        jCBagama1 = new javax.swing.JComboBox<>();
        jCBstatus1 = new javax.swing.JComboBox<>();
        jCBgodar1 = new javax.swing.JComboBox<>();
        jRBwna1 = new javax.swing.JRadioButton();
        jRBwni1 = new javax.swing.JRadioButton();
        jTFpekerjaan1 = new javax.swing.JTextField();
        jBreset1 = new javax.swing.JButton();
        jBregister1 = new javax.swing.JButton();
        jLfoto1 = new javax.swing.JLabel();
        jBchoose1 = new javax.swing.JButton();
        jLpoto1 = new javax.swing.JLabel();
        jP = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLnama2 = new javax.swing.JLabel();
        jLttl2 = new javax.swing.JLabel();
        jLjk2 = new javax.swing.JLabel();
        jLalamat2 = new javax.swing.JLabel();
        jLrt2 = new javax.swing.JLabel();
        jLdesa2 = new javax.swing.JLabel();
        jLkec = new javax.swing.JLabel();
        jLkota2 = new javax.swing.JLabel();
        jLagama2 = new javax.swing.JLabel();
        jLstatus2 = new javax.swing.JLabel();
        jLpekerjaan2 = new javax.swing.JLabel();
        jLkewarganegaraan2 = new javax.swing.JLabel();
        jLtmpt = new javax.swing.JLabel();
        jLtl = new javax.swing.JLabel();
        jLjko = new javax.swing.JLabel();
        jLalamato = new javax.swing.JLabel();
        jLrto = new javax.swing.JLabel();
        jLrw = new javax.swing.JLabel();
        jLdesao = new javax.swing.JLabel();
        jLkeco = new javax.swing.JLabel();
        jLkotao = new javax.swing.JLabel();
        jLagamao = new javax.swing.JLabel();
        jLstatuso = new javax.swing.JLabel();
        jLpekerjaano = new javax.swing.JLabel();
        jLkewarganegaraano = new javax.swing.JLabel();
        jBexit = new javax.swing.JButton();
        jLnamao = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLgodar = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jPhome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBhome = new javax.swing.JButton();
        jBform = new javax.swing.JButton();
        jBkeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPform.setBackground(new java.awt.Color(0, 204, 204));

        jLformktp1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLformktp1.setText("FORM KARTU TANDA PENDUDUK");

        jLformisian1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLformisian1.setForeground(new java.awt.Color(255, 255, 255));
        jLformisian1.setText("FORM ISIAN");

        jLnama1.setText("Nama");

        jLttl1.setText("Tempat/Tanggal Lahir");

        jLjk1.setText("Jenis Kelamin");

        jLalamat1.setText("Alamat");

        jLrt1.setText("RT/RW");

        jLdesa1.setText("Kel/Desa");

        jLkecamatan1.setText("Kecamatan");

        jLkota1.setText("Kota");

        jLagama1.setText("Agama");

        jLstatus1.setText("Status");

        jLgoldar1.setText("Golongan Darah");

        jLpekerjaan1.setText("Pekerjaan");

        jLkewarganegaraan1.setText("Kewarganegaraan");

        buttonGroup1.add(jRBperempuan1);
        jRBperempuan1.setText("Perempuan");

        jLabel3.setText("/");

        jTFtl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFtl1ActionPerformed(evt);
            }
        });

        jLabel4.setText("/");

        buttonGroup1.add(jRBlaki1);
        jRBlaki1.setText("Laki-laki");

        jCBagama1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISLAM", "KRISTEN", "BUDHA", "KATOLIK", " " }));

        jCBstatus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KAWIN", "BELUM KAWIN" }));

        jCBgodar1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));

        buttonGroup2.add(jRBwna1);
        jRBwna1.setText("WNA");

        buttonGroup2.add(jRBwni1);
        jRBwni1.setText("WNI");
        jRBwni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBwni1ActionPerformed(evt);
            }
        });

        jBreset1.setText("Reset");
        jBreset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreset1ActionPerformed(evt);
            }
        });

        jBregister1.setText("Register");
        jBregister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregister1ActionPerformed(evt);
            }
        });

        jLfoto1.setText("FOTO");

        jBchoose1.setText("Choose");
        jBchoose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBchoose1ActionPerformed(evt);
            }
        });

        jLpoto1.setText("jLabel3");

        javax.swing.GroupLayout jPformLayout = new javax.swing.GroupLayout(jPform);
        jPform.setLayout(jPformLayout);
        jPformLayout.setHorizontalGroup(
            jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPformLayout.createSequentialGroup()
                .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPformLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLformktp1))
                    .addGroup(jPformLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLformisian1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPformLayout.createSequentialGroup()
                .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPformLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLnama1)
                            .addComponent(jLttl1)
                            .addComponent(jLjk1)
                            .addComponent(jLalamat1)))
                    .addGroup(jPformLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLdesa1)
                            .addComponent(jLrt1)
                            .addComponent(jLkecamatan1)
                            .addComponent(jLkota1)))
                    .addGroup(jPformLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLagama1))
                    .addGroup(jPformLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLstatus1))
                    .addGroup(jPformLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLgoldar1))
                    .addGroup(jPformLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLkewarganegaraan1))
                    .addGroup(jPformLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLpekerjaan1)))
                .addGap(34, 34, 34)
                .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTFkota1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFkec1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFalamat1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBstatus1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBgodar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBagama1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPformLayout.createSequentialGroup()
                        .addComponent(jTFRT1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(jTFRW1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPformLayout.createSequentialGroup()
                        .addComponent(jRBwna1)
                        .addGap(18, 18, 18)
                        .addComponent(jRBwni1))
                    .addComponent(jTFnama1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBlaki1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPformLayout.createSequentialGroup()
                        .addComponent(jTFttl1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBperempuan1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFtl1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                    .addComponent(jTFdesa1)
                    .addComponent(jTFpekerjaan1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPformLayout.createSequentialGroup()
                        .addComponent(jBchoose1)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPformLayout.createSequentialGroup()
                        .addComponent(jLfoto1)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPformLayout.createSequentialGroup()
                        .addComponent(jLpoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPformLayout.createSequentialGroup()
                        .addComponent(jBreset1)
                        .addGap(55, 55, 55)
                        .addComponent(jBregister1)
                        .addGap(95, 95, 95))))
        );
        jPformLayout.setVerticalGroup(
            jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPformLayout.createSequentialGroup()
                .addComponent(jLformktp1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLformisian1)
                .addGap(18, 18, 18)
                .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnama1)
                    .addComponent(jTFnama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPformLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLttl1)
                            .addComponent(jTFttl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFtl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(13, 13, 13)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLjk1)
                            .addComponent(jRBperempuan1)
                            .addComponent(jRBlaki1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLalamat1)
                            .addComponent(jTFalamat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLrt1)
                            .addComponent(jTFRT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFRW1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLdesa1)
                            .addComponent(jTFdesa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLkecamatan1)
                            .addComponent(jTFkec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLkota1)
                            .addComponent(jTFkota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLagama1)
                            .addComponent(jCBagama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLstatus1)
                            .addComponent(jCBstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLgoldar1)
                            .addComponent(jCBgodar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLpekerjaan1)
                            .addComponent(jTFpekerjaan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLkewarganegaraan1)
                            .addComponent(jRBwna1)
                            .addComponent(jRBwni1)
                            .addComponent(jBreset1)
                            .addComponent(jBregister1)))
                    .addGroup(jPformLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLfoto1)
                        .addGap(18, 18, 18)
                        .addComponent(jLpoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBchoose1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPform, "card3");

        jP.setBackground(new java.awt.Color(102, 102, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Kartu Tanda Penduduk (KTP)");

        jLnama2.setText("Nama");

        jLttl2.setText("Tempat/Tanggal Lahir");

        jLjk2.setText("Jenis Kelamin");

        jLalamat2.setText("Alamat");

        jLrt2.setText("RT/RW");

        jLdesa2.setText("Kel/Desa");

        jLkec.setText("Kecamatan");

        jLkota2.setText("Kota");

        jLagama2.setText("Agama");

        jLstatus2.setText("Status");

        jLpekerjaan2.setText("Pekerjaan");

        jLkewarganegaraan2.setText("Kewarganegaraan");

        jLtmpt.setText("jlabel3");

        jLtl.setText("jLabel4");

        jLjko.setText("jLabel5");

        jLalamato.setText("jLabel7");

        jLrto.setText("jLabel8");

        jLrw.setText("jLabel9");

        jLdesao.setText("jLabel10");

        jLkeco.setText("jLabel11");

        jLkotao.setText("jLabel12");

        jLagamao.setText("jLabel13");

        jLstatuso.setText("jLabel14");

        jLpekerjaano.setText("jLabel15");

        jLkewarganegaraano.setText("jLabel16");

        jBexit.setText("Exit");
        jBexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexitActionPerformed(evt);
            }
        });

        jLnamao.setText("jLabel2");

        jLabel6.setText("Golongan Darah");

        jLgodar.setText("jLabel3");

        label.setText("jLabel3");

        javax.swing.GroupLayout jPLayout = new javax.swing.GroupLayout(jP);
        jP.setLayout(jPLayout);
        jPLayout.setHorizontalGroup(
            jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLayout.createSequentialGroup()
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLayout.createSequentialGroup()
                                            .addComponent(jLnama2)
                                            .addGap(146, 146, 146))
                                        .addGroup(jPLayout.createSequentialGroup()
                                            .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLttl2)
                                                .addComponent(jLjk2)
                                                .addGroup(jPLayout.createSequentialGroup()
                                                    .addGap(29, 29, 29)
                                                    .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLkec)
                                                        .addComponent(jLdesa2)
                                                        .addComponent(jLkota2)
                                                        .addComponent(jLrt2))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPLayout.createSequentialGroup()
                                        .addComponent(jLalamat2)
                                        .addGap(140, 140, 140)))
                                .addGroup(jPLayout.createSequentialGroup()
                                    .addComponent(jLagama2)
                                    .addGap(140, 140, 140)))
                            .addGroup(jPLayout.createSequentialGroup()
                                .addComponent(jLstatus2)
                                .addGap(142, 142, 142)))
                        .addGroup(jPLayout.createSequentialGroup()
                            .addComponent(jLpekerjaan2)
                            .addGap(125, 125, 125)))
                    .addGroup(jPLayout.createSequentialGroup()
                        .addComponent(jLkewarganegaraan2)
                        .addGap(85, 85, 85)))
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLstatuso)
                    .addComponent(jLnamao)
                    .addGroup(jPLayout.createSequentialGroup()
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLagamao)
                            .addComponent(jLalamato)
                            .addComponent(jLjko)
                            .addComponent(jLdesao)
                            .addGroup(jPLayout.createSequentialGroup()
                                .addComponent(jLrto)
                                .addGap(37, 37, 37)
                                .addComponent(jLrw))
                            .addComponent(jLkeco)
                            .addComponent(jLkotao)
                            .addGroup(jPLayout.createSequentialGroup()
                                .addComponent(jLtmpt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLtl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
            .addGroup(jPLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPLayout.createSequentialGroup()
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(130, 130, 130)
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLpekerjaano)
                            .addComponent(jLgodar)
                            .addComponent(jLkewarganegaraano)))
                    .addGroup(jPLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jBexit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPLayout.setVerticalGroup(
            jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnama2)
                    .addComponent(jLnamao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPLayout.createSequentialGroup()
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLttl2)
                            .addComponent(jLtmpt)
                            .addComponent(jLtl))
                        .addGap(13, 13, 13)
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLjk2)
                            .addComponent(jLjko))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLalamat2)
                            .addComponent(jLalamato))
                        .addGap(11, 11, 11)
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLrt2)
                            .addComponent(jLrto)
                            .addComponent(jLrw))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLdesa2)
                            .addComponent(jLdesao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLkec)
                            .addComponent(jLkeco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLkota2)
                            .addComponent(jLkotao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLagama2)
                            .addComponent(jLagamao)))
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLstatus2)
                    .addComponent(jLstatuso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLgodar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLpekerjaan2)
                    .addComponent(jLpekerjaano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLkewarganegaraan2)
                    .addComponent(jLkewarganegaraano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBexit)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jP, "card4");

        jPhome.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POSTEST3/IMG_0900.JPG"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("KOTA BALIKPAPAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel10)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPhomeLayout = new javax.swing.GroupLayout(jPhome);
        jPhome.setLayout(jPhomeLayout);
        jPhomeLayout.setHorizontalGroup(
            jPhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPhomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPhomeLayout.setVerticalGroup(
            jPhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPhomeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPhome, "card2");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));

        jBhome.setText("Home");
        jBhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhomeActionPerformed(evt);
            }
        });

        jBform.setText("Form");
        jBform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBformActionPerformed(evt);
            }
        });

        jBkeluar.setText("Exit");
        jBkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBkeluarActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POSTEST3/images.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DINAS KEPENDIDIKAN DAN CATATAN SIPIL");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("(DISDUKCAPIL)");

        jLabel9.setText("Kota Balikpapan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBhome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBform)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBkeluar)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))))
                        .addContainerGap(278, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBhome)
                    .addComponent(jBform)
                    .addComponent(jBkeluar)))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFtl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFtl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFtl1ActionPerformed

    private void jRBwni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBwni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBwni1ActionPerformed

    private void jBreset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreset1ActionPerformed
        // TODO add your handling code here:
        jTFnama1.setText("");
        jTFttl1.setText("");
        jTFtl1.setText("");
        buttonGroup1.clearSelection();
        jTFalamat1.setText("");
        jTFRT1.setText("");
        jTFRW1.setText("");
        jTFdesa1.setText("");
        jTFkec1.setText("");
        jTFkota1.setText("");
        jCBagama1.setSelectedItem(null);
        jCBstatus1.setSelectedItem(null);
        jCBgodar1.setSelectedItem(null);
        jTFpekerjaan1.setText("");
        buttonGroup2.clearSelection();
        // semua sintaks diatas membuat semua variabel yang ada di panel output1 akan mengambil semua nilai dari variabel yang ada di panel pform
    
    }//GEN-LAST:event_jBreset1ActionPerformed

    private void jBregister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregister1ActionPerformed
        // TODO add your handling code here:
        String Nama, ttl, tl, JK=null, Alamat, RT, RW, desa, Kec, kota, agama, status, godar, pekerjaan;
        Nama = jTFnama1.getText();
        ttl = jTFttl1.getText();
        tl = jTFtl1.getText();
        if (jRBlaki1.isSelected())
        {JK = jRBlaki1.getText();}
        else if (jRBperempuan1.isSelected())
        {JK =jRBperempuan1.getText();}
        Alamat =jTFalamat1.getText();
        RT = jTFRT1.getText();
        RW = jTFRW1.getText();
        desa = jTFdesa1.getText();
        Kec = jTFkec1.getText();
        kota = jTFkota1.getText();
        agama = jCBagama1.getSelectedItem().toString();
        status = jCBstatus1.getSelectedItem().toString();
        godar = jCBgodar1.getSelectedItem().toString();
        pekerjaan = jTFpekerjaan1.getText();
        String kewarganegaraan=null;
        if (jRBwna1.isSelected())
        {kewarganegaraan = jRBwni1.getText();}
        else if (jRBwni1.isSelected())
        {kewarganegaraan = jRBwna1.getText();}

        output x = new output(Nama, ttl, tl, JK, Alamat, RT, RW, desa, Kec, kota, agama, status, godar, pekerjaan, kewarganegaraan);
        // semua sintaks diatas untuk mengeset nilai dari setiap variabel menjadi kosong atau menghapus nilai yang sudah di input 

        jP.setVisible(true);
        jPform.setVisible(false);
    }//GEN-LAST:event_jBregister1ActionPerformed

    private void jBchoose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBchoose1ActionPerformed
        // TODO add your handling code here:
        JFileChooser OPEN = new JFileChooser();
        int returnVal = OPEN.showOpenDialog(null);

        File filegambar = null;
        if (returnVal == JFileChooser.APPROVE_OPTION){
            filegambar=OPEN.getSelectedFile();
            String filename = filegambar.getAbsolutePath();
        }
        try {
            BufferedImage gambar=ImageIO.read(filegambar);
            ImageIcon icon=new ImageIcon(gambar.getScaledInstance(180,240,0));
            jLpoto1.setIcon(icon);
            output outt =new output(icon);
            outt.setVisible(true);

        }
        catch (IOException e){e.getMessage();}
    }//GEN-LAST:event_jBchoose1ActionPerformed

    private void jBexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBexitActionPerformed

    private void jBhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhomeActionPerformed
        // TODO add your handling code here:
        jPhome.setVisible(true);
        jPform.setVisible(false);
    }//GEN-LAST:event_jBhomeActionPerformed

    private void jBformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBformActionPerformed
        // TODO add your handling code here:
        jPform.setVisible(true);
        jPhome.setVisible(false);
    }//GEN-LAST:event_jBformActionPerformed

    private void jBkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(postest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(postest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(postest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(postest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new postest3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBchoose1;
    private javax.swing.JButton jBexit;
    private javax.swing.JButton jBform;
    private javax.swing.JButton jBhome;
    private javax.swing.JButton jBkeluar;
    private javax.swing.JButton jBregister1;
    private javax.swing.JButton jBreset1;
    private javax.swing.JComboBox<String> jCBagama1;
    private javax.swing.JComboBox<String> jCBgodar1;
    private javax.swing.JComboBox<String> jCBstatus1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLagama1;
    private javax.swing.JLabel jLagama2;
    private javax.swing.JLabel jLagamao;
    private javax.swing.JLabel jLalamat1;
    private javax.swing.JLabel jLalamat2;
    private javax.swing.JLabel jLalamato;
    private javax.swing.JLabel jLdesa1;
    private javax.swing.JLabel jLdesa2;
    private javax.swing.JLabel jLdesao;
    private javax.swing.JLabel jLformisian1;
    private javax.swing.JLabel jLformktp1;
    private javax.swing.JLabel jLfoto1;
    private javax.swing.JLabel jLgodar;
    private javax.swing.JLabel jLgoldar1;
    private javax.swing.JLabel jLjk1;
    private javax.swing.JLabel jLjk2;
    private javax.swing.JLabel jLjko;
    private javax.swing.JLabel jLkec;
    private javax.swing.JLabel jLkecamatan1;
    private javax.swing.JLabel jLkeco;
    private javax.swing.JLabel jLkewarganegaraan1;
    private javax.swing.JLabel jLkewarganegaraan2;
    private javax.swing.JLabel jLkewarganegaraano;
    private javax.swing.JLabel jLkota1;
    private javax.swing.JLabel jLkota2;
    private javax.swing.JLabel jLkotao;
    private javax.swing.JLabel jLnama1;
    private javax.swing.JLabel jLnama2;
    private javax.swing.JLabel jLnamao;
    private javax.swing.JLabel jLpekerjaan1;
    private javax.swing.JLabel jLpekerjaan2;
    private javax.swing.JLabel jLpekerjaano;
    private javax.swing.JLabel jLpoto1;
    private javax.swing.JLabel jLrt1;
    private javax.swing.JLabel jLrt2;
    private javax.swing.JLabel jLrto;
    private javax.swing.JLabel jLrw;
    private javax.swing.JLabel jLstatus1;
    private javax.swing.JLabel jLstatus2;
    private javax.swing.JLabel jLstatuso;
    private javax.swing.JLabel jLtl;
    private javax.swing.JLabel jLtmpt;
    private javax.swing.JLabel jLttl1;
    private javax.swing.JLabel jLttl2;
    private javax.swing.JPanel jP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPform;
    private javax.swing.JPanel jPhome;
    private javax.swing.JRadioButton jRBlaki1;
    private javax.swing.JRadioButton jRBperempuan1;
    private javax.swing.JRadioButton jRBwna1;
    private javax.swing.JRadioButton jRBwni1;
    private javax.swing.JTextField jTFRT1;
    private javax.swing.JTextField jTFRW1;
    private javax.swing.JTextField jTFalamat1;
    private javax.swing.JTextField jTFdesa1;
    private javax.swing.JTextField jTFkec1;
    private javax.swing.JTextField jTFkota1;
    private javax.swing.JTextField jTFnama1;
    private javax.swing.JTextField jTFpekerjaan1;
    private javax.swing.JTextField jTFtl1;
    private javax.swing.JTextField jTFttl1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
